#E14.1JSON2CSV.PY import
JSON FR = OPEN("PRICE2016.JSON","R") LS = JSON.LOAD(FR) DATA = [ LIST(LS[0].KEYS()) ] PRINT(DATA) for
ITEM in LS: DATA.APPEND(LIST(ITEM.VALUES())) FR.CLOSE() FW = OPEN("PRICE2016JSON2CSV.CSV","W") for
X in DATA: FW.WRITE(",".JOIN(X)+"\N") FW.CLOSE()  
